
services:
  db:
    ports:
      - "5433:5432" 

  backend:
    ports:
      - "8080:8080" 
    volumes:
      - ./backend/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  #--- Serviço do Front-end (em modo de desenvolvimento) ---
#  frontend:
#    container_name: ceasa_frontend_dev
#    build:
#      context: ./frontend
#      target: builder # Usa apenas o primeiro estágio do Dockerfile para rodar o servidor de dev
#    volumes:
#      - ./frontend:/app 
#    ports:
#      - "3000:3000" 
#    environment:
#      - NODE_ENV=development
#    command: npm start 
#    depends_on:
#     - backend
#    networks:
#      - ceasa-network