
TRUNCATE
    tb_pedido_itens, tb_carrinho_itens, tb_carrinhos,
    tb_ofertas_produtor, tb_metas_estoque, tb_produtor_produto,
    tb_perfis_entregador, tb_perfis_produtor, tb_produtos, tb_pedidos, tb_user, tb_role
RESTART IDENTITY CASCADE;




INSERT INTO tb_produtos (nome, unidade_de_medida, preco, foto_url, descricao) VALUES
('Abacaxi', 'Un.', 6.50, 'Abacaxi.jpg', NULL),
('Abacate', 'Kg', 120.00, 'Abacate.jpg', NULL),
('Abóbora Preta', 'Kg', 65.00, 'Abóbora Preta.jpg', NULL),
('Abobrinha', 'Kg', 55.00, 'Abobrinha.jpg', NULL),
('Alho 4°', 'Kg', 135.00, 'Alho 4°.jpg', NULL),
('Alho Chinês', 'Kg', 200.00, 'Alho Chinês.jpg', NULL),
('Ameixa', 'Kg', 16.00, 'Ameixa.jpg', NULL),
('Banana Preta', 'Kg', 90.00, 'Banana Preta.jpg', NULL),
('Banana Caturra', 'Kg', 60.00, 'Banana Caturra.jpg', NULL),
('Banana da Terra', 'Un.', 120.00, 'Banana da Terra.jpg', NULL),
('Batata Doce B.', 'Kg', 55.00, 'Batata Doce B.jpg', NULL),
('Batata Doce Ver.', 'Kg', 55.00, 'Batata Doce Ver.jpg', NULL),
('Batata Inglesa E', 'Kg', 65.00, 'Batata Inglesa E.jpg', NULL),
('Batata Diversa (Fraca)', 'Kg', 55.00, 'Batata Diversa (Fraca).jpg', NULL),
('Berinjela', 'Kg', 40.00, 'Berinjela.jpg', NULL),
('Beterraba 1°', 'Kg', 70.00, 'Beterraba 1°.jpg', NULL),
('Beterraba 2°', 'Kg', 60.00, 'Beterraba 2°.jpg', NULL),
('Cebola B. Cx 2 (M)', 'Kg', 40.00, 'Cebola B. Cx 2 (M).jpg', NULL),
('Cebola B. Cx 3 (G)', 'Kg', 45.00, 'Cebola B. Cx 3 (G).jpg', NULL),
('Cebola Roxa', 'Kg', 60.00, 'Cebola Roxa.jpg', NULL),
('Cenoura 1°', 'Kg', 72.00, 'Cenoura 1°.jpg', NULL),
('Cenoura 2°', 'Kg', 60.00, 'Cenoura 2°.jpg', NULL),
('Chuchu (Preto)', 'Kg', 80.00, 'Chuchu (Preto).jpg', NULL),
('Coco Seco', 'Un.', 3.00, 'Coco Seco.jpg', NULL),
('Couve-Flor (Saco)', 'Un.', 65.00, 'Couve-Flor (Saco).jpg', NULL),
('Gengibre', 'Kg', 100.00, 'Gengibre.jpg', NULL),
('Goiaba', 'Kg', 100.00, 'Goiaba.jpg', NULL),
('Jiló', 'Kg', 40.00, 'Jiló.jpg', NULL),
('Inhame Paulista', 'Kg', 120.00, 'Inhame Paulista.jpg', NULL),
('Inhame Cará', 'Kg', 110.00, 'Inhame Cará.jpg', NULL),
('Kiwi', 'Kg', 240.00, 'Kiwi.jpg', NULL),
('Laranja', 'Un.', 50.00, 'Laranja.jpg', NULL),
('Limão Taity', 'Cx.', 90.00, 'Limão Taity.jpg', NULL),
('Limão Merim', 'Kg', 110.00, 'Limão Merim.jpg', NULL),
('Maçã 198 (Pequena)', 'Kg', 165.00, 'Maçã 198 (Pequena).jpg', NULL),
('Maçã Verde', 'Kg', 220.00, 'Maçã Verde.jpg', NULL),
('Maçã 135 (grande)', 'Kg', 175.00, 'Maçã 135 (grande).jpg', NULL),
('Maçã Argentil', 'Kg', 220.00, 'Maçã Argentil.jpg', NULL),
('Mamão Havaí', 'Kg', 40.00, 'Mamão Havaí.jpg', NULL),
('Mamão Formosa', 'Kg', 50.00, 'Mamão Formosa.jpg', NULL),
('Mandioca', 'Kg', 45.00, 'Mandioca.jpg', NULL),
('Manga Palmer (G)', 'Kg', 85.00, 'Manga Palmer (G).jpg', NULL),
('Manga Espada', 'Kg', 70.00, 'Manga Espada.jpg', NULL),
('Manga Rosa', 'Kg', 100.00, 'Manga Rosa.jpg', NULL),
('Manga Tommy', 'Kg', 90.00, 'Manga Tommy.jpg', NULL),
('Maracujá Cx.', 'Kg', 100.00, 'Maracujá Cx.jpg', NULL),
('Maxixe', 'Kg', 50.00, 'Maxixe.jpg', NULL),
('Melancia', 'Kg', 1.40, 'Melancia.jpg', NULL),
('Melão Caixa', 'Un.', 110.00, 'Melão Caixa.jpg', NULL),
('Melão Rei', 'Un.', 120.00, 'Melão Rei.jpg', NULL),
('Melão Saco (Unidade)', 'Un.', 70.00, 'Melão Saco (Unidade).jpg', NULL),
('Milho Verde', '100 Un.', 100.00, 'Milho Verde.jpg', NULL),
('Morango Cx. c/ 40bandejas', 'Un.', 20.00, 'Morango Cx. c 40bandejas.jpg', NULL),
('Ovo branco', 'Un.', 190.00, 'Ovo branco.jpg', NULL),
('Pepino', 'Kg', 40.00, 'Pepino.jpg', NULL),
('Pêra 90', 'Kg', 170.00, 'Pêra 90.jpg', NULL),
('Pimentão Maduro', 'Kg', 50.00, 'Pimentão Maduro.jpg', NULL),
('Ponkan', 'Kg', 75.00, 'Ponkan.jpg', NULL),
('Quiabo', 'Kg', 150.00, 'Quiabo.jpg', NULL),
('Repolho Verde', 'Kg', 50.00, 'Repolho Verde.jpg', NULL),
('Repolho Roxo', 'Kg', 80.00, 'Repolho Roxo.jpg', NULL),
('Tomate 1°', 'Kg', 60.00, 'Tomate 1°.jpg', NULL),
('Tomate 2°', 'Kg', 45.00, 'Tomate 2°.jpg', NULL),
('Uva Roxa', 'Kg', 200.00, 'Uva Roxa.jpg', NULL),
('Uva S Semente', 'Kg', 180.00, 'Uva S Semente.jpg', NULL),
('Uva Verde', 'Kg', 210.00, 'Uva Verde.jpg', NULL)
ON CONFLICT (id) DO NOTHING;



