INSERT INTO tb_produtos (nome, unidade_de_medida, preco, foto_url, descricao) VALUES
('Abacaxi', 'Un.', 6.50, '/produtos/Abacaxi.jpg', NULL),
('Abacate', 'Kg', 120.00, '/produtos/Abacate.jpg', NULL),
('Abóbora Preta', 'Kg', 65.00, '/produtos/Abóbora Preta.jpg', NULL),
('Abobrinha', 'Kg', 55.00, '/produtos/Abobrinha.jpg', NULL),
('Alho 4°', 'Kg', 135.00, '/produtos/Alho 4°.jpg', NULL),
('Alho Chinês', 'Kg', 200.00, '/produtos/Alho Chinês.jpg', NULL),
('Ameixa', 'Kg', 16.00, '/produtos/Ameixa.jpg', NULL),
('Banana Preta', 'Kg', 90.00, '/produtos/Banana Preta.jpg', NULL),
('Banana Caturra', 'Kg', 60.00, '/produtos/Banana Caturra.jpg', NULL),
('Banana da Terra', 'Un.', 120.00, '/produtos/Banana da Terra.jpg', NULL),
('Batata Doce B.', 'Kg', 55.00, '/produtos/Batata Doce B.jpg', NULL),
('Batata Doce Ver.', 'Kg', 55.00, '/produtos/Batata Doce Ver.jpg', NULL),
('Batata Inglesa E', 'Kg', 65.00, '/produtos/Batata Inglesa E.jpg', NULL),
('Batata Diversa (Fraca)', 'Kg', 55.00, '/produtos/Batata Diversa (Fraca).jpg', NULL),
('Berinjela', 'Kg', 40.00, '/produtos/Berinjela.jpg', NULL),
('Beterraba 1°', 'Kg', 70.00, '/produtos/Beterraba 1°.jpg', NULL),
('Beterraba 2°', 'Kg', 60.00, '/produtos/Beterraba 2°.jpg', NULL),
('Cebola B. Cx 2 (M)', 'Kg', 40.00, '/produtos/Cebola B. Cx 2 (M).jpg', NULL),
('Cebola B. Cx 3 (G)', 'Kg', 45.00, '/produtos/Cebola B. Cx 3 (G).jpg', NULL),
('Cebola Roxa', 'Kg', 60.00, '/produtos/Cebola Roxa.jpg', NULL),
('Cenoura 1°', 'Kg', 72.00, '/produtos/Cenoura 1°.jpg', NULL),
('Cenoura 2°', 'Kg', 60.00, '/produtos/Cenoura 2°.jpg', NULL),
('Chuchu (Preto)', 'Kg', 80.00, '/produtos/Chuchu (Preto).jpg', NULL),
('Coco Seco', 'Un.', 3.00, '/produtos/Coco Seco.jpg', NULL),
('Couve-Flor (Saco)', 'Un.', 65.00, '/produtos/Couve-Flor (Saco).jpg', NULL),
('Gengibre', 'Kg', 100.00, '/produtos/Gengibre.jpg', NULL),
('Goiaba', 'Kg', 100.00, '/produtos/Goiaba.jpg', NULL),
('Jiló', 'Kg', 40.00, '/produtos/Jiló.jpg', NULL),
('Inhame Paulista', 'Kg', 120.00, '/produtos/Inhame Paulista.jpg', NULL),
('Inhame Cará', 'Kg', 110.00, '/produtos/Inhame Cará.jpg', NULL),
('Kiwi', 'Kg', 240.00, '/produtos/Kiwi.jpg', NULL),
('Laranja', 'Un.', 50.00, '/produtos/Laranja.jpg', NULL),
('Limão Taity', 'Cx.', 90.00, '/produtos/Limão Taity.jpg', NULL),
('Limão Merim', 'Kg', 110.00, '/produtos/Limão Merim.jpg', NULL),
('Maçã 198 (Pequena)', 'Kg', 165.00, '/produtos/Maçã 198 (Pequena).jpg', NULL),
('Maçã Verde', 'Kg', 220.00, '/produtos/Maçã Verde.jpg', NULL),
('Maçã 135 (grande)', 'Kg', 175.00, '/produtos/Maçã 135 (grande).jpg', NULL),
('Maçã Argentil', 'Kg', 220.00, '/produtos/Maçã Argentil.jpg', NULL),
('Mamão Havaí', 'Kg', 40.00, '/produtos/Mamão Havaí.jpg', NULL),
('Mamão Formosa', 'Kg', 50.00, '/produtos/Mamão Formosa.jpg', NULL),
('Mandioca', 'Kg', 45.00, '/produtos/Mandioca.jpg', NULL),
('Manga Palmer (G)', 'Kg', 85.00, '/produtos/Manga Palmer (G).jpg', NULL),
('Manga Espada', 'Kg', 70.00, '/produtos/Manga Espada.jpg', NULL),
('Manga Rosa', 'Kg', 100.00, '/produtos/Manga Rosa.jpg', NULL),
('Manga Tommy', 'Kg', 90.00, '/produtos/Manga Tommy.jpg', NULL),
('Maracujá Cx.', 'Kg', 100.00, '/produtos/Maracujá Cx.jpg', NULL),
('Maxixe', 'Kg', 50.00, '/produtos/Maxixe.jpg', NULL),
('Melancia', 'Kg', 1.40, '/produtos/Melancia.jpg', NULL),
('Melão Caixa', 'Un.', 110.00, '/produtos/Melão Caixa.jpg', NULL),
('Melão Rei', 'Un.', 120.00, '/produtos/Melão Rei.jpg', NULL),
('Melão Saco (Unidade)', 'Un.', 70.00, '/produtos/Melão Saco (Unidade).jpg', NULL),
('Milho Verde', '100 Un.', 100.00, '/produtos/Milho Verde.jpg', NULL),
('Morango Cx. c/ 40bandejas', 'Un.', 20.00, '/produtos/Morango Cx. c 40bandejas.jpg', NULL),
('Ovo branco', 'Un.', 190.00, '/produtos/Ovo branco.jpg', NULL),
('Pepino', 'Kg', 40.00, '/produtos/Pepino.jpg', NULL),
('Pêra 90', 'Kg', 170.00, '/produtos/Pêra 90.jpg', NULL),
('Pimentão Maduro', 'Kg', 50.00, '/produtos/Pimentão Maduro.jpg', NULL),
('Ponkan', 'Kg', 75.00, '/produtos/Ponkan.jpg', NULL),
('Quiabo', 'Kg', 150.00, '/produtos/Quiabo.jpg', NULL),
('Repolho Verde', 'Kg', 50.00, '/produtos/Repolho Verde.jpg', NULL),
('Repolho Roxo', 'Kg', 80.00, '/produtos/Repolho Roxo.jpg', NULL),
('Tomate 1°', 'Kg', 60.00, '/produtos/Tomate 1°.jpg', NULL),
('Tomate 2°', 'Kg', 45.00, '/produtos/Tomate 2°.jpg', NULL),
('Uva Roxa', 'Kg', 200.00, '/produtos/Uva Roxa.jpg', NULL),
('Uva S Semente', 'Kg', 180.00, '/produtos/Uva S Semente.jpg', NULL),
('Uva Verde', 'Kg', 210.00, '/produtos/Uva Verde.jpg', NULL)
ON CONFLICT (id) DO UPDATE 
SET 
    nome = EXCLUDED.nome,
    unidade_de_medida = EXCLUDED.unidade_de_medida,
    preco = EXCLUDED.preco,
    foto_url = EXCLUDED.foto_url,
    descricao = EXCLUDED.descricao;